- name: "Configure timesyncd"
  ansible.builtin.copy:
    src: timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes
  notify: restart timesyncd

- name: "Start timesyncd service"
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: yes
    state: started
