- name: "Install snmpd"
  ansible.builtin.apt:
    update_cache: yes
    name: snmpd
    state: present

- name: "Retrieve SNMP community"
  ansible.builtin.set_fact:
    community_string: "{{ lookup('community.general.hashi_vault', 'secret=secret/data/infrastructure/celestia:community_string') }}"
  run_once: true
  delegate_to: localhost

- name: "Configure SNMP"
  ansible.builtin.template:
    src: snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: "0600"
    backup: yes
  notify: restart snmpd

  # Script downloaded from https://gitlab.com/observium/distroscript
- name: "Copy distro script from Observium"
  ansible.builtin.copy:
    src: distro
    dest: /usr/bin/distro
    owner: root
    group: root
    mode: "0755"
  notify: restart snmpd

- name: "Start SNMP service"
  ansible.builtin.systemd:
    name: snmpd
    state: started
    enabled: yes

- name: "Force handlers to restart snmpd for the configuration to be OK when adding in Observium"
  ansible.builtin.meta: flush_handlers

- name: "Add servers to Observium"
  ansible.builtin.command: "/opt/observium/add_device.php {{ ansible_hostname }} {{ community_string }} {{ snmp_version }}"
  register: add_device
  changed_when: '"Added device" in add_device.stdout'
  failed_when: '"Devices failed" in add_device.stdout and "Already got device" not in add_device.stdout'
  ignore_errors: yes
  delegate_to: argos
