- name: "Install snmpd"
  ansible.builtin.apt:
    update_cache: yes
    name: snmpd
    state: present

- name: "Retrieve SNMPv3 password and passphrase"
  ansible.builtin.set_fact:
    snmp_authpass: "{{ lookup('community.general.hashi_vault', 'secret=secret/data/infrastructure/mercure:snmp_authpass') }}"
    snmp_cryptopass: "{{ lookup('community.general.hashi_vault', 'secret=secret/data/infrastructure/mercure:snmp_cryptopass') }}"
  run_once: true
  delegate_to: localhost
  become: no

- name: Gather facts using SNMP version 3
  community.general.snmp_facts:
    host: '{{ inventory_hostname }}'
    version: v3
    level: authPriv
    integrity: sha
    privacy: aes
    username: '{{ snmp_user }}'
    authkey: '{{ snmp_authpass }}'
    privkey: '{{ snmp_cryptopass }}'
  ignore_errors: yes
  delegate_to: localhost
  become: no
  register: snmp_facts_results

- name: "Configure SNMP"
  ansible.builtin.template:
    src: snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: "0600"
    backup: yes
  notify: restart snmpd

- name: Setup SNMP v3 user
  block:
    - name: "Stop SNMP service"
      ansible.builtin.systemd:
        name: snmpd
        state: stopped
      
    - name: CreateUser in /var/lib/snmp/snmpd.conf
      ansible.builtin.lineinfile:
        path: /var/lib/snmp/snmpd.conf
        state: present
        line: 'createUser {{ snmp_user }} SHA {{ snmp_authpass }} AES {{ snmp_cryptopass }}'

  when: snmp_facts_results.failed

- name: "Start SNMP service"
  ansible.builtin.systemd:
    name: snmpd
    state: started
    enabled: yes

- name: "Force handlers to restart snmpd for the configuration to be OK when adding in Observium"
  ansible.builtin.meta: flush_handlers
