- name: "Install snmpd"
  ansible.builtin.apt:
    update_cache: yes
    name: snmpd
    state: present

- name: "Retrieve SNMP community"
  ansible.builtin.set_fact:
    community_string: "{{ lookup('community.general.hashi_vault', 'secret=secret/data/infrastructure/celestia:community_string') }}"
  run_once: true
  delegate_to: localhost

- name: "Configure SNMP"
  ansible.builtin.template:
    src: snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: "0600"
    backup: yes
  notify: restart snmpd

  # Script downloaded from https://gitlab.com/observium/distroscript
- name: "Copy script Observium"
  ansible.builtin.copy:
    src: distro
    dest: /usr/bin/distro
    owner: root
    group: root
    mode: "0755"
  notify: restart snmpd

- name: "Copy list of servers to monitor to Observium"
  ansible.builtin.template:
    src: add_device_input.j2
    dest: /root/devices_list.txt
  run_once: true
  delegate_to: ubuntu-ansible-2 # TODO: argos

- name: "Add servers to Observium"
  ansible.builtin.command: ls # TODO: "/opt/observium/add_device.php /root/devices_list.txt"
  register: add_device
  changed_when: ' "Already got device" not in add_device.stdout '
  failed_when: '"Could not resolve" in add_device.stdout'
  run_once: true
  delegate_to: ubuntu-ansible-2 #TODO: argos

- name: "Delete devices list from Observium"
  ansible.builtin.file:
    path: /root/devices_list.txt
    state: absent
  run_once: true
  delegate_to: ubuntu-ansible-2 # TODO: argos
