vault_agent_working_directory: /root/vault_agent_certificates

vault_agent_vault_version: 1.18.2

vault_agent_certificate_directory: "/var/lib/vault_certificates"

# vault_agent_service_reload_command:
# vault_agent_group_name: "vault-certs"
