- name: "Install Network UPS tool"
  ansible.builtin.apt:
    update_cache: yes
    name: nut
    state: present

- name: "Retrieve vault credentials for NUT"
  ansible.builtin.set_fact:
    admin_pass: "{{ lookup('community.hashi_vault.vault_kv2_get', 'infrastructure/nut').secret.admin }}"
    nutcli_pass: "{{ lookup('community.hashi_vault.vault_kv2_get', 'infrastructure/nut').secret.nutcli }}"
  run_once: true
  delegate_to: localhost

- name: "Configure NUT"
  ansible.builtin.copy:
    src: nut.conf
    dest: /etc/nut/nut.conf
  notify: restart nut-server

- name: "Configure UPS device"
  ansible.builtin.template:
    src: ups.conf.j2 
    dest: /etc/nut/ups.conf
  notify: restart nut-server

- name: "Configure UPS users"
  ansible.builtin.template:
    src: upsd.users.j2 
    dest: /etc/nut/ups.users
  notify: restart nut-server